version: '2.0'

services:
  peer-base: # peer的公共服务
    image: hyperledger/fabric-peer:2.4.1
    extra_hosts:
      - "orderer.qq.com:192.168.1.2"
      - "peer0.taobao.com:192.168.208.129"
      - "peer1.taobao.com:192.168.208.129"
      - "peer0.jd.com:192.168.208.129"
      - "peer1.jd.com:192.168.208.129"
    environment:
      - GODEBUG=netdns=go
      - FABRIC_LOGGING_SPEC=INFO
      - FABRIC_LOGGING_FORMAT="%{color}%{time:2006-01-02 15:04:05.000 MST} [%{module}] %{shortfunc} -> %{level:.4s} %{id:03x}%{color:reset} %{message}"
      - CORE_CHAINCODE_BUILDER=hyperledger/fabric-ccenv:2.4.1
      - CORE_CHAINCODE_GOLANG_RUNTIME=hyperledger/fabric-baseos:2.4.1
      - CORE_VM_ENDPOINT=unix:///var/run/docker.sock
      - CORE_LOGGING_PEER=info
      - CORE_CHAINCODE_LOGGING_LEVEL=INFO
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/peer/msp # msp证书（节点证书）
      #- CORE_LEDGER_STATE_STATEDATABASE=goleveldb # 状态数据库的存储引擎（or CouchDB）
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=fabric_network # docker 网络
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: peer node start
    networks:
      - fabric_network
