version: '2'

networks:
  fabric_network:
    name: fabric_netwotk
    
services:

  ca-tls:
    container_name: ca-tls
    image: hyperledger/fabric-ca:1.4.7
    environment:
      - FABRIC_CA_SERVER_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_CSR_CN=ca-tls
      # - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server/ca.qq.com-cert.pem
      # - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server/priv_sk
      - FABRIC_CA_SERVER_CSR_HOSTS=0.0.0.0
      - FABRIC_CA_SERVER_DEBUG=true
      - FABRIC_CA_SERVER_DB_TYPE=mysql
      - FABRIC_CA_SERVER_DB_DATASOURCE=root:123456@tcp(192.168.208.129:3306)/fabric_ca_tls?parseTime=true
    volumes:
      - ./crypto-config/ordererOrganizations/qq.com/ca/:/etc/hyperledger/fabric-ca-server
    # command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server/ca.qq.com-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server/priv_sk -d -b tls-ca-admin:tls-ca-adminpw --port 7054'
    command: sh -c 'fabric-ca-server start -d -b tls-ca-admin:tls-ca-adminpw --port 7054'
    networks:
      - fabric_network
    ports:
      - 7054:7054
      
  ca-taobao:
    image: hyperledger/fabric-ca:1.4.7
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-taobao
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      # - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server/ca.taobao.com-cert.pem
      # - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server/priv_sk
      - FABRIC_CA_SERVER_CSR_HOSTS=0.0.0.0
      - FABRIC_CA_SERVER_DEBUG=true
      - FABRIC_CA_SERVER_DB_TYPE=mysql
      - FABRIC_CA_SERVER_DB_DATASOURCE=root:123456@tcp(192.168.208.129:3306)/fabric_ca_tb?parseTime=true
    ports:
      - "8054:7054"
    # command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server/ca.taobao.com-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server/priv_sk -b tb-ca-admin:tb-ca-adminpw -d --port 8054'
    command: sh -c 'fabric-ca-server start -d -b tb-ca-admin:tb-ca-adminpw --port 8054'
    volumes:
      - ./crypto-config/peerOrganizations/taobao.com/ca/:/etc/hyperledger/fabric-ca-server
    container_name: ca-taobao
    networks:
      - fabric_network
      
  ca-jd:
    image: hyperledger/fabric-ca:1.4.7
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-jd
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      # - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server/ca.jd.com-cert.pem
      # - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server/priv_sk
      - FABRIC_CA_SERVER_CSR_HOSTS=0.0.0.0
      - FABRIC_CA_SERVER_DEBUG=true
      - FABRIC_CA_SERVER_DB_TYPE=mysql
      - FABRIC_CA_SERVER_DB_DATASOURCE=root:123456@tcp(192.168.208.129:3306)/fabric_ca_jd?parseTime=true
    ports:
      - "9054:7054"
    # command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server/ca.jd.com-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server/priv_sk -b jd-ca-admin:jd-ca-adminpw -d --port 9054'
    command: sh -c 'fabric-ca-server start -d -b jd-ca-admin:jd-ca-adminpw --port 9054'
    volumes:
      - ./crypto-config/peerOrganizations/jd.com/ca/:/etc/hyperledger/fabric-ca-server
    container_name: ca-jd
    networks:
      - fabric_network

